language: go

go:
  - "1.13.x"

go_import_path: go.dedis.ch/onet/v3

script:
  - env GO111MODULE=on make test

matrix:
  include:
    - name: "64-bit Unit Tests"
      env: GOARCH=amd64
    - name: "32-bit Unit Tests"
      env: GOARCH=386

notifications:
  email: false

# https://restic.net/blog/2018-09-02/travis-build-cache
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
